name: CCT
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - aiohttp=3.7.3=py39hbd71b63_0
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - bottleneck=1.3.2=py39hdd57654_1
  - brotlipy=0.7.0=py39h38d8fee_1001
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_0
  - cffi=1.14.6=py39h400218f_0
  - click=8.0.1=py39hf3d152e_0
  - coverage=5.3=py39h07f9747_1
  - cryptography=3.4.7=py39hbca0aa6_0
  - dataclasses=0.8=pyhc8e2a94_3
  - gast=0.4.0=pyh9f0ad1d_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - h5py=2.10.0=nompi_py39h25020de_105
  - hdf5=1.10.6=nompi_h3c11f04_101
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.8.1=py39hf3d152e_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - joblib=1.0.1=pyhd3eb1b0_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39h51133e4_0
  - multidict=4.7.5=py39h07f9747_2
  - ncurses=6.2=he6710b0_1
  - numexpr=2.7.3=py39h22e1b3c_1
  - numpy-base=1.20.3=py39h74d4b33_0
  - openssl=1.1.1l=h7f8727e_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - pandas=1.3.4=py39h8c16a72_0
  - pip=21.0.1=py39h06a4308_0
  - pyasn1=0.4.8=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_3
  - python=3.9.2=hdb3f193_0
  - python-flatbuffers=2.0=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd3eb1b0_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scikit-learn=0.24.2=py39ha9443f7_0
  - scipy=1.6.2=py39had2a1c9_1
  - setuptools=52.0.0=py39h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorflow=2.4.1=mkl_py39h4683426_0
  - tensorflow-base=2.4.1=mkl_py39h43e0292_0
  - tensorflow-estimator=2.5.0=pyh81a9013_1
  - termcolor=1.1.0=py_2
  - threadpoolctl=2.2.0=pyhbf3da8f_0
  - tk=8.6.10=hbc83047_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzdata=2020f=h52ac0ba_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py39hbd71b63_2
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py39hbd71b63_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.12.0
    - argon2-cffi==20.1.0
    - backcall==0.2.0
    - bleach==4.0.0
    - cachetools==4.2.1
    - chardet==4.0.0
    - cycler==0.10.0
    - cython==0.29.22
    - debugpy==1.4.1
    - decorator==4.4.2
    - defusedxml==0.7.1
    - dominate==2.6.0
    - einops==0.3.2
    - entrypoints==0.3
    - google-auth==1.28.1
    - google-auth-oauthlib==0.4.4
    - grpcio==1.37.0
    - imageio==2.9.0
    - ipykernel==6.2.0
    - ipython==7.26.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==7.0.1
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - kmodes==0.11.0
    - kornia==0.5.2
    - markupsafe==2.0.1
    - matplotlib==3.4.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.4
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - notebook==6.4.3
    - numpy==1.20.2
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - packaging==21.0
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - protobuf==3.15.8
    - ptyprocess==0.7.0
    - pyasn1-modules==0.2.8
    - pydensecrf==1.0rc2
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.1
    - pywavelets==1.1.1
    - pyzmq==22.2.1
    - qtconsole==5.1.1
    - qtpy==1.10.0
    - scikit-image==0.18.1
    - scratchai-nightly==0.0.1a3
    - send2trash==1.8.0
    - sewar==0.4.4
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - terminado==0.11.1
    - testpath==0.5.0
    - tifffile==2021.4.8
    - torch==1.8.1
    - torchvision==0.9.1
    - tornado==6.1
    - tqdm==4.60.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - vit-pytorch==0.20.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1

